---

# ansible-galaxy role install -r requirements.yml
roles:

  - name: eessi.cvmfs
    src: https://github.com/EESSI/ansible-cvmfs
    version: be935e0

  - name: geerlingguy.repo-epel
    version: 3.0.0
