# Install CVMFS Stratum 1 server(s).
---
- name: CVMFS Stratum 1
  hosts: cvmfsstratum1servers
  roles:
    - role: geerlingguy.repo-epel
      when: ansible_facts['os_family'] == 'RedHat'
    - eessi.cvmfs
    - cvmfs_server_meta_info
...
