---
- name: Create a meta.json containing the CVMFS Server Meta Information
  ansible.builtin.copy:
    content: "{{ cvmfs_server_meta | to_nice_json(indent=2, sort_keys=false) }}"
    dest: "{{ cvmfs_srv_mount }}/cvmfs/info/v1/meta.json"
    owner: root
    group: root
    mode: 0644
  become: true
  when: (cvmfs_repositories | default(eessi_cvmfs_repositories, true) | length) > 0

- name: Create meta information for each CVMFS repository
  ansible.builtin.include_tasks: repo_meta_info.yml
  vars:
    this_cvmfs_repo: "{{ item }}"
    this_cvmfs_repo_meta:
      description: "{{ item.description | default(omit) }}"
      recommended-stratum0: "http://{{ item.stratum0 }}/cvmfs/{{ item.repository }}"
      recommended-stratum1s: "{{ eessi_cvmfs_server_urls | selectattr('domain', 'in', item.repository) |
                                 map(attribute='urls') | map('regex_replace', '@fqrn@', item.repository) }}"
  with_items: "{{ cvmfs_repositories | default(eessi_cvmfs_repositories, true) }}"
  when: ('cvmfsstratum0servers' in group_names and inventory_hostname in groups['cvmfsstratum0servers']) or cvmfs_role == 'stratum0'
...
