name: Test ingest-tarball.sh script

on:
  push:
    branches:
      - main
    paths:
      - scripts/ingest-tarball.sh
      - scripts/test-ingest-tarball.sh
  pull_request:
    branches:
      - main
    paths:
      - scripts/ingest-tarball.sh
      - scripts/test-ingest-tarball.sh

# Declare default permissions as read only.
permissions: read-all

jobs:
  test-ingestion-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0

      - name: run tarball ingestion test script
        run: |
            scripts/test-ingest-tarball.sh
